api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
#    formats:
#        json:
#            mime_types: ['application/json']
    eager_loading:
        enabled: true
    collection:
        pagination:
#            enabled: false
            page_parameter_name: _page
#            client_enabled: true
#            enabled_parameter_name: pagination
            items_per_page: 10
            client_items_per_page: true # Disabled by default
            items_per_page_parameter_name: itemsPerPage
            maximum_items_per_page: 20
            partial: false
            client_partial: true
            partial_parameter_name: 'partial'
    exception_to_status:
        App\Exception\EmptyBodyException: 400
        App\Exception\InvalidConfirmationTokenException: 404
